### ISSUE TITLE
モジュールの設置場所について

### ISSUE THREAD

**Issue by harada5000** [KeisukeIwabuchi/MQL4-Slack#1]
こんにちわ
Webサイトより技術の高さを感じましてお邪魔しました。

GitHubというものに詳しくないのですが、モジュールのファイルを設置する場所ですが
＜MQL4/Include/ ...>以下に配置で良いのでしょうか？
＜MQL4/Includes/ ...>と２種類あるようですが　どちらにしたら良いでしょうか？

**Comment by KeisukeIwabuchi** [comment]
こんにちわ
サイト見ていただいて光栄です。

これはMT4のヘッダーファイル保存場所（デフォルトで存在するフォルダ）を指しています。
GitHubのReadmeでは**Includes**となっておりますが、MT4のヘッダーファイル保存場所は**Include**が正しかったです。

混乱させてしまい申し訳ございませんでした。
Readmeの記載は近々修正いたします。

**Include**フォルダの中に保存してご利用ください。

**Comment by KeisukeIwabuchi** [comment]
Readmeを修正しました。
